name: "JFrog Upload Action"
description: "Upload dummy artifact to JFrog Artifactory"
inputs:
  jfrog-url:
    description: "JFrog Artifactory URL"
    required: true
  jfrog-username:
    description: "JFrog username"
    required: true
  jfrog-token:
    description: "JFrog access token"
    required: true
  repo:
    description: "Target repository in Artifactory"
    required: true
  file:
    description: "File to upload"
    required: true
  target-path:
    description: "Path in Artifactory"
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup JFrog CLI
      shell: bash
      run: |
        curl -fL https://getcli.jfrog.io | sh
        sudo mv jfrog /usr/local/bin/

    - name: Configure JFrog CLI
      shell: bash
      run: |
        jfrog config add my-server \
          --artifactory-url "${{ inputs.jfrog-url }}" \
          --user "${{ inputs.jfrog-username }}" \
          --access-token "${{ inputs.jfrog-token }}" \
          --interactive=false \
          --overwrite 

    - name: Upload Artifact
      shell: bash
      run: |
        jfrog rt u "${{ inputs.file }}" "${{ inputs.repo }}/${{ inputs.target-path }}/"

