name: 'Hello World'
description: 'Greet someone'
inputs:
  repository:
    description: "repo owner / name"
    default: ${{ github.repository }}
  token:
    description: "github token"
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
      - uses: actions/checkout@v3
      - run: |
          echo ${{ github.workspace }}
          echo $GITHUB_WORKSPACE
        shell: bash
      -run: |
        python3 writeJson.py \
          --github-repository="${{ inputs.repository }}" \
          --github-token="${{ inputs.token }}"
      shell: bash
  

