name: "Custom Test Action"
description: "A reusable GitHub Action for testing on a self-hosted runner"
author: "bhushanls"

inputs:
  message:
    description: "Message to display"
    required: false
    default: "Hello from Custom Action"

runs:
  using: "composite"
  steps:
    - name: Print message
      run: echo "${{ inputs.message }}"
      shell: bash
