name: 'Hello World'
description: 'Greet someone'
inputs:
  repository:
    description: "repo owner / name"
    default: ${{ github.repository }}
  token:
    description: "github token"
    default: ${{ github.token }}
  env:
  
runs:
  using: "composite"
  steps:
      - uses: actions/checkout@v3
        #working-directory: ./actions
      - run: |
          echo ${{ github.workspace }}
          echo $GITHUB_WORKSPACE
        shell: bash
      - run: |
          python3 /home/kpit/actions-runner/_work/_actions/bhushanvelis/actions/v1/testAction/writeJson.py \
            --github-repository="${{ inputs.repository }}" \
            --github-token="${{ inputs.token }}"
          pwd
        shell: bash
  

